SmartTrafficMonitoring/SmartTrafficMonitoring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('homepage.urls', namespace='homepage')),
    path("", include('task.urls', namespace='task')),
    path("user/", include('user.urls', namespace='user')),
    path("accounts/", include("allauth.urls")),
]

SmartTrafficMonitoring/task/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'task'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create-task/', views.create_task, name='create_task'),
    path('view-task/<int:task_id>', views.view_task, name='view_task'),
    path('update-task/<int:task_id>', views.update_task, name='update_task'),
    path('delete-task/<int:task_id>', views.delete_task, name='delete_task'),
    path('search-task', views.search_task, name='search_task'),
    path('custom-loop/<int:task_id>', views.custom_loop, name='custom_loop'),
    path('clear-loop/<int:task_id>', views.clear_loop, name='clear_loop'),
    path('delete-loop/<int:task_id>/<int:loop_id>', views.delete_loop, name='delete_loop'),
    path('schedule/<int:task_id>', views.schedule, name='schedule'),
    path('notification/', views.view_notification, name='view_notification'),
    path('map/', views.map, name='map'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SmartTrafficMonitoring/user/urls.py
from django.urls import path
from user.views import ChangePasswordView


from . import views
app_name = 'user'

urlpatterns = [
    #path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('profile', views.profile, name='profile'),
    path('change_pw', ChangePasswordView.as_view(), name='change_pw'),
    path('create_user', views.create_user, name='create_user'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
]

SmartTrafficMonitoring/user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class RoleID(models.Model):
    name = models.CharField(max_length = 30)

    def __str__(self):
        return f"{self.name} "

    # def creat_role(self):
    #     pass
    # def view_role(self):
    #     pass
    # def update_role(self):
    #     pass
    # def delete_role(self):
    #     pass


class UserInfo(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_id")
    role_id = models.ForeignKey(RoleID, on_delete=models.CASCADE, related_name="role_id")
    phone_number = models.CharField(max_length=10)
    

    def __str__(self):
        return f'{ self.user_id.username } { self.role_id }'
    
    # def creat_user(self):
    #     pass
    # def view_user(self):
    #     pass
    # def update_user(self):
    #     pass
    # def delete_user(self):
    #     pass
    # def login(self):
    #     pass
    # def logout(self):
    #     pass

SmartTrafficMonitoring/user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserInfo, RoleID


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(max_length=10, required=False, help_text='Optional.', widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone_number']

    def __init__(self, *args, **kwargs):
        super(UpdateUserForm, self).__init__(*args, **kwargs)
        try:
            # set the initial value of phone_number field to user's phone_number value in UserInfo
            user_info = UserInfo.objects.get(user_id=self.instance)
            self.fields['phone_number'].initial = user_info.phone_number
        except UserInfo.DoesNotExist:
            pass

    def save(self, commit=True):
        # save the phone_number value to UserInfo
        user_info, _ = UserInfo.objects.get_or_create(user_id=self.instance)
        user_info.phone_number = self.cleaned_data['phone_number']
        user_info.save()
        return super().save(commit)

class UserCreationForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=10)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
            'role_id': forms.HiddenInput(attrs={'value': 3}),
            'role_id_id': forms.HiddenInput(),
            'role_id__name': forms.TextInput(attrs={'disabled': True}),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            UserInfo.objects.create(user_id=user, role_id_id=3, phone_number=self.cleaned_data['phone_number'])
        return user

SmartTrafficMonitoring/user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import  UpdateUserForm, UserCreationForm
from .models import UserInfo
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin

import sys
sys.path.append("..")
from task.models import *

log_in = 'user/login.html'

def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('task:index'))
        else:
            return render(request, log_in, {
                'message': 'Invalid credentials.'
            })
    return render(request, log_in)

def logout_view(request):
    logout(request)
    return render(request, log_in, {
                'message': 'You are logged out.'
            })


@login_required(login_url='/user/login')
def profile(request):    
    user_info = UserInfo.objects.get(user_id=request.user)
    phone_number = user_info.phone_number
    role_id = user_info.role_id.name
    context = {'phone_number': phone_number, 'role_id': role_id}
    return render(request, 'user/profile.html', context)

def create_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'User created successfully!')
        
        return redirect('user:login')
    else:
        form = UserCreationForm()
        if request.user.is_authenticated:
            return redirect('task:index')
    return render(request, 'user/create_user.html', {'form': form})

def edit_profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'User updated successfully!')
            return redirect('user:profile')
    else:
        try:
            user_info = UserInfo.objects.get(user_id=request.user)
            phone_number = user_info.phone_number
        except UserInfo.DoesNotExist:
            phone_number = ''
        initial_data = {
            'username': request.user.username,
            'email': request.user.email,
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'phone_number': phone_number,
        }
        user_form = UpdateUserForm(initial=initial_data)
    return render(request, 'user/edit_profile.html', {'user_form': user_form})

class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'user/change_pw.html'
    success_message = "Successfully Changed Your Password"
    success_url = '/user/login'

SmartTrafficMonitoring/user/templates/user/change_pw.html
{% extends 'task/layout.html' %}
{% load static %}
{% block body %}
<div class="change-pw">
  <div class="container">
    <div class="change-pw-head">
      <h1 class="head mb-4">Change Your Password</h1>
      {% if form.errors %}
      <div class="alert alert-danger alert-dismissible" role="alert">
        <div id="form_errors">
          {% for key, value in form.errors.items %}
          <strong>{{ value }}</strong>
          {% endfor %}
        </div>
        <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> -->
      </div>
      {% endif %}
    </div>

    <form method="POST">
      {% csrf_token %}
      <label class="un" for="id_old_password">Old Password</label>
      <input type="password" name="old_password" autocomplete="new-password" class="pass" required id="id_old_password"
        placeholder="Enter Old Password" />

      <label class="un" for="id_new_password1">New Password</label>
      <input type="password" name="new_password1" autocomplete="new-password" class="pass" required
        id="id_new_password1" placeholder="Enter New Password" />

      <label class="un" for="id_new_password2">New Password Confirmation</label>
      <input type="password" name="new_password2" autocomplete="new-password" required id="id_new_password2"
        class="pass" placeholder="Confirm New Password" />

      <div class="submit-area mt-2">
        <button type="submit" class="submit submit-btn" id="reset">
          Update Password
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

SmartTrafficMonitoring/user/templates/user/create_user.html
{% extends 'task/layout.html' %}
{% load static %}
{% block body %}

<div class="create-user-container">
    <h1>Create User</h1>
    <section class="create-user-detail">
        <form method="post" action="{% url 'user:create_user' %}">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input class="form-control username" type="text" id="username" name="username" required><br>

            <label for="first_name">First Name:</label>
            <input class="form-control first" type="text" id="first_name" name="first_name" required>

            <label for="last_name">Last Name:</label>
            <input class="form-control last" type="text" id="last_name" name="last_name" required><br>

            <label for="email">Email:</label>
            <input class="form-control email" type="email" id="email" name="email" >

            <label for="phone_number">Phone Number:</label>
            <input class="form-control phone" type="text" id="phone_number" name="phone_number" maxlength="10"><br>

            <label for="password">Password:</label>
            <input class="form-control password" type="password" id="password" name="password" required><br>

            <button type="submit" class="create-user-btn">Create</button>
        </form>
    </section>
</div>

{% endblock %}

SmartTrafficMonitoring/user/templates/user/edit_profile.html
{% extends 'task/layout.html' %}
{% load static %}
{% block body %}

<div class="edit-profile-container mb-0">
    <h1>Edit Profile</h1>
    <div class="edit-profile-detail">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label>Username: {{ user_form.username }} </label>
            <br>
            <br>
            <label>Email: {{ user_form.email }}</label>
            <br>
            <br>
            <label>Name: {{ user_form.first_name }}</label>
            <br>
            <br>
            <label>Surname: {{ user_form.last_name }}</label>
            <br>
            <br>
            <label>Phone Number: {{ user_form.phone_number }}</label>
            <br>
            <div class="edit-options-btn">
                <button type="reset" class="reset-btn">Reset</button>
                <button type="submit" class="save-btn">Save Changes</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

SmartTrafficMonitoring/user/templates/user/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/style.css' %}">
    <title>Login</title>
</head>
<body>
<div class="wrapper">
    <h2>LOGIN</h2>
    {% if message %}
    <div  style="color:red">{{ message }}</div>
    {% endif %}
    <form class="form1" action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        <div class="username-area username">
            <div class="input-box username">
                <input class="username" name="username" type="text" placeholder="Username">
            </div>
        </div>
        <div class="password-area password">
            <div class="input-box password">
                <input class="password" name="password" type="password" placeholder="Password">
            </div>
        </div>
        <button class="submit" name="submit" type="submit">Login</button>
        <a href="{% url 'user:create_user' %}" class="create-acc">Create Account</a><br>
        {% load socialaccount %}
        <button class="google-login">
            <a href="{% provider_login_url 'google' %}?next=/" >Login with Google</a>
        </button>
    </form>
</div>
</body>
</html>

SmartTrafficMonitoring/user/templates/user/profile.html
{% extends 'task/layout.html' %}
{% load static %}
{% block body %}

<div class="view-profile-container d-flex justify-content-center align-items-center">
    <div>
        <div class="profile-header mb-4">
            <h1 class="text-center">Profile</h1>
        </div>
        <div class="profile-info">
            <div class="mb-3">
                <strong>Name:</strong> {{ user.first_name }} {{ user.last_name }}
            </div>
            <div class="mb-3">
                <strong>Email:</strong> {{ user.email }}
            </div>
            <div class="mb-3">
                <strong>Phone Number:</strong> {{ phone_number }}
            </div>
            <div class="mb-3">
                <strong>Role:</strong> {{ role_id }}
            </div>
        </div>
        <div class="options-btn mt-4 d-flex justify-content-center">
            <a href="{% url 'user:edit_profile' %}" class="btn btn-primary">Edit Profile</a>
            <a href="{% url 'user:change_pw' %}" class="btn btn-secondary">Change Password</a>
        </div>
    </div>
</div>

{% endblock %}