SmartTrafficMonitoring/SmartTrafficMonitoring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('homepage.urls', namespace='homepage')),
    path("", include('task.urls', namespace='task')),
    path("user/", include('user.urls', namespace='user')),
    path("accounts/", include("allauth.urls")),
]

SmartTrafficMonitoring/task/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'task'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create-task/', views.create_task, name='create_task'),
    path('view-task/<int:task_id>', views.view_task, name='view_task'),
    path('update-task/<int:task_id>', views.update_task, name='update_task'),
    path('delete-task/<int:task_id>', views.delete_task, name='delete_task'),
    path('search-task', views.search_task, name='search_task'),
    path('custom-loop/<int:task_id>', views.custom_loop, name='custom_loop'),
    path('clear-loop/<int:task_id>', views.clear_loop, name='clear_loop'),
    path('delete-loop/<int:task_id>/<int:loop_id>', views.delete_loop, name='delete_loop'),
    path('schedule/<int:task_id>', views.schedule, name='schedule'),
    path('notification/', views.view_notification, name='view_notification'),
    path('map/', views.map, name='map'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SmartTrafficMonitoring/user/urls.py
from django.urls import path
from user.views import ChangePasswordView


from . import views
app_name = 'user'

urlpatterns = [
    #path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('profile', views.profile, name='profile'),
    path('change_pw', ChangePasswordView.as_view(), name='change_pw'),
    path('create_user', views.create_user, name='create_user'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
]

SmartTrafficMonitoring/task/models.py
from django.db import models
from django.contrib.auth.models import User

class Status(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.name}"

class Task(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    latitude = models.FloatField(max_length=64, null=True, blank=True)
    longitude = models.FloatField(max_length=64, null=True, blank=True)
    loop = models.FileField(upload_to='loop/', null=True, blank=True)
    input_vdo = models.FileField(upload_to='vdo_input/', null=True, blank=True)
    output_vdo = models.FileField(upload_to='vdo_output/', null=True, blank=True)
    report = models.FileField(upload_to='report_output/', null=True, blank=True)
    status_id = models.ForeignKey(
        Status, on_delete=models.CASCADE, related_name="status_id")
    note = models.CharField(max_length=255, blank=True)
    preset = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="created_by")
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return f"{self.name} {self.location}"

class UploadFile(models.Model):
    video_file = models.FileField(upload_to='videos/')
    loop_txt_file = models.FileField(upload_to='texts/')

    def __str__(self):
        return f"{self.video_file} {self.loop_txt_file}"
    
class Notification(models.Model):
    detail = models.CharField(max_length=255)
    task = models.ForeignKey(
        Task, on_delete=models.CASCADE, related_name="task_id")
    already_read = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notification_for")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.created_by} {self.detail}"

SmartTrafficMonitoring/task/forms.py
from django import forms
from .models import Task

class TaskForm(forms.Form):
    name = forms.CharField(label="Name: ", max_length=255)  
    location  = forms.CharField(label="Location: ", max_length=255) 
    loop = forms.FileField(label="Loop")
    input_vdo = forms.FileField(label="Video")
    note = forms.CharField(label="Note: ", max_length=255, required=False) 

    class Meta:
        model = Task
        fields = ["name", "location", "loop", "input_vdo", "note"]

SmartTrafficMonitoring/task/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.utils import dateformat
from . import loop
import os, cv2, json
from django.conf import settings

import sys
sys.path.append("../user")
sys.path.append("../SmartTrafficMonitoring")

from SmartTrafficMonitoring.scheduler_adapter import CeleryAdapter
from user.models import UserInfo
from .models import *
from drone.views import CheckDrone
from drone.models import Weather

@login_required(login_url='/user/login')
def index(request):
    user_info = UserInfo.objects.get(user_id=request.user)

    # tasks = Task.objects.filter(created_by=request.user)
    tasks = Task.objects.all()

    for task in tasks:
        task.created_at = dateformat.format(task.created_at, 'd/m/Y')
        task.updated_at = dateformat.format(task.updated_at, 'd/m/Y')

    if len(tasks) == 0:
        message = "You need to create task."
    else:
        message = None

    return render(request, 'task/index.html', {
        'user': request.user,
        'user_info': user_info,
        'tasks': tasks,
        'message': message
    })

@login_required(login_url='/user/login')
def create_task(request):
    if request.method == 'POST':
        if request.FILES['input_vdo']:
            if request.POST.get('input_type', 'new') == 'new':
                name = request.POST.get('name', None)
                location = request.POST.get('location', None)
            else:
                task_id = request.POST.get('task_id', None)
                task = Task.objects.get(pk=task_id)

                name = task.name
                location = task.location
            
            fs = FileSystemStorage()

            # video stuff
            input_vdo = request.FILES['input_vdo']
            input_vdo_filename = fs.save(input_vdo.name, input_vdo)
            uploaded_input_vdo_url = fs.url(input_vdo_filename) # = task.input_vdo

            # loop stuff
            file_choice = request.POST.get('file-choice')
            # if request.FILES.get('loop'):
            if file_choice == "custom" :
                # custom loop
                loop_file = request.FILES['loop']
                loop_filename = fs.save(loop_file.name, loop_file)
            # else:
            elif file_choice == "default" :
                # default loop
                default_path = os.path.join(settings.BASE_DIR, 'loop.json')
                media_file_path = os.path.join(settings.MEDIA_ROOT, 'loop.json')
                with open(default_path, 'rb') as f: #rb = read & binary
                    loop_filename = fs.save(media_file_path, f)
            elif file_choice == "border" :
                # get video
                video_path = os.path.join(settings.MEDIA_ROOT, str(uploaded_input_vdo_url).split("/")[-1])
                video = cv2.VideoCapture(video_path)
                # get video width&length
                height = video.get(cv2.CAP_PROP_FRAME_HEIGHT)
                width = video.get(cv2.CAP_PROP_FRAME_WIDTH)
                
                # make 4 loops, each at video border
                # copy the default loop file?
                default_path = os.path.join(settings.BASE_DIR, 'loop.json')
                media_file_path = os.path.join(settings.MEDIA_ROOT, 'loop.json')
                with open(default_path, 'rb') as f: #rb = read & binary
                    loop_filename = fs.save(media_file_path, f)
                
                # get path to the copied loop file
                loop_path = os.path.join(settings.MEDIA_ROOT, str(fs.url(loop_filename)).split("/")[-1]) #used as filename?

                # clear all current loop
                loop.clear_loop(loop_path)

                # add loops at border
                h = height
                w = width
                l = 10 # loop width?
                loop.write_json(loop_path,"loop0","0",[0, l, l, 0],[0, l, h-l, h],"clockwise")
                loop.write_json(loop_path,"loop1","1",[0, l, w-l, w],[0, l, l, 0],"clockwise")
                loop.write_json(loop_path,"loop2","2",[w, w-l, w-l, w],[0, l, h-l, h],"clockwise")
                loop.write_json(loop_path,"loop3","3",[0, l, w-l, w],[h, h-l, h-l, h],"clockwise")

            uploaded_loop_url = fs.url(loop_filename)

            note = request.POST.get('note', None)
            preset = request.POST.get('preset', False)
            latitude = request.POST.get('latitude')
            flag = True
            try:
                float(latitude)
            except ValueError:
                    flag = False
            if flag:
                latitude = float(latitude)
            else:
                latitude = 14.068542
            longitude = request.POST.get('longitude', None)
            flag = True
            try:
                float(longitude)
            except ValueError:
                    flag = False
            if flag:
                longitude = float(longitude)
            else:
                longitude = 100.605965

            task = Task.objects.create(
                name = name,
                location = location,
                loop = uploaded_loop_url,
                input_vdo = uploaded_input_vdo_url,
                status_id = Status.objects.first(),
                note = note,
                preset = preset,
                created_by = request.user,
                latitude = latitude,
                longitude = longitude
            )
            weather = Weather.objects.create(task = task, location="Loading. Please refresh to load"
            , wind_speed=0, latitude=latitude, longitude=longitude, 
            temp=0, weather_report='', humidity=0, clouds = 0)
            
            return HttpResponseRedirect(reverse('task:custom_loop', args=(task.id,)))
        else:
            return redirect(reverse('task:create_task'))

    else:
        preset_tasks = Task.objects.filter(created_by=request.user, preset=True)
        
        return render(request, 'task/create_task.html', {
            'user': request.user,
            'preset_tasks': preset_tasks
        })
    
@login_required(login_url='/user/login')
def view_task(request, task_id):
    weather = Weather.objects.get(task=task_id)
    task = Task.objects.filter(pk=task_id).first()
    CheckDrone(request,task_id = task, lat = weather.latitude ,lon = weather.longitude)

    Notification.objects.filter(task=task).update(
        already_read = True
    )

    my_task = Task.objects.get(id=task_id)
    rows = []
    if my_task.report:
        file_path = my_task.report.path
        
        with open(file_path, 'r') as f:
            for line in f:
                fields = line.strip().split(',')
                row_dict = {
                    'loop': fields[0],
                    'track': fields[1],
                    'vehicle': fields[2],
                    'time': fields[3],
                    'direction': fields[4],
                }
                rows.append(row_dict)
        
        report_url = my_task.report.url
    else:
        report_url = None
    if task is None:
        return redirect(reverse('task:index'))

    return render(request, 'task/view_task.html', {
                'rows': rows,
                'user': request.user,
                'task': task,
                'output_vdo': task.output_vdo.url if task.output_vdo else '',
                'report_url': report_url,
                'weather' : weather,
            })

@login_required(login_url='/user/login')
def update_task(request, task_id):
    task = Task.objects.filter(pk=task_id, created_by=request.user).first()

    if task is None:
        return redirect(reverse('task:index'))
    else:
        if request.method == 'POST':
            name = request.POST.get('name')
            latitude = request.POST.get('latitude')
            longitude = request.POST.get('longitude')

            fs = FileSystemStorage()

            try:
                loop = request.FILES['loop']
                loop_filename = fs.save(loop.name, loop)
                uploaded_loop_url = fs.url(loop_filename)
            except:
                uploaded_loop_url = task.loop

            try:
                input_vdo = request.FILES['input_vdo']
                input_vdo_filename = fs.save(input_vdo.name, input_vdo)
                uploaded_input_vdo_url = fs.url(input_vdo_filename)
            except:
                uploaded_input_vdo_url = task.input_vdo

            location = request.POST.get('location')
            note = request.POST.get('note')
            weather = Weather.objects.get(task=task_id)
            flag = True
            try:
                float(latitude)
            except ValueError:
                flag = False
            if flag:
                latitude = float(latitude)
            else:
                latitude = weather.latitude
            flag = True
            try:
                float(longitude)
            except ValueError:
                flag = False
            if flag:
                longitude = float(longitude)
            else:
                longitude = weather.longitude
            weather.latitude = latitude
            weather.longitude = longitude
            weather.save()
            Task.objects.filter(pk=task_id).update(
                name = name,
                loop = uploaded_loop_url,
                input_vdo = uploaded_input_vdo_url,
                location = location,
                note = note,
                latitude = latitude,
                longitude = longitude
            )

            # update timestamp (updated_at)
            Task.objects.get(pk=task_id).save()

            return HttpResponseRedirect(reverse('task:view_task', args=(task.id,)))
        else:
            return render(request, 'task/update_task.html', {

SmartTrafficMonitoring/task/templates/task/custom_loop.html
{% extends 'task/layout.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="/static/task/css/style.css">
{% endblock %}

{% block body %}

<div class="container">
    <h1>Loop Management</h1>
    {% if frame %}
    <div class="m-4">
        <div class="d-flex upload-header">
            <p class="step">Step 4</p>
            <p class="m-2">Custom loop</p>
        </div>
        <p>&emsp;&ensp;Fill loop's datas and click "add loop's data" to add or update loop. Click "Confirm Creation" when every things done.</p>
    </div>
    <div class="custom-loop m-5">
        <img id ="capframe" src="{{ MEDIA_URL }}/{{ frame }}" alt="car capture frame"><br>
        
        <!-- For putting loop list -->
        {% if loops %}
        <div class="report-table" id="loops-table">
            <table class="table table-hover">
                <tr>
                    <th> Id</th>
                    <th> Loop Name </th>
                    <th> Point 1</th>
                    <th> Point 2</th>
                    <th>Point 3</th>
                    <th>Point 4</th>
                    <th>Delete</th>
                </tr>
                {% for loop in loops %}
                <tr>
                    <td>{{loop.id}}</td>
                    <td>{{loop.name}}</td>
                    {% for point in loop.points %}
                        <td>({{point.x}}, {{point.y}})</td>
                    {% endfor %}
                    <!-- <td> <a href="{% url 'task:delete_loop' task_id loop.id %}" class="delete-loop"> Delete </a> </td> -->
                    <td> <a href="/delete-loop/{{task_id}}/{{loop.id}}#capframe" class="delete-loop"> Delete </a> </td>
                {% endfor %}
                </tr>
            </table>
        </div>
        {% endif %}

        <a href="{% url 'task:clear_loop' task_id %}"><button class="clear-loop-btn">Clear all loop</button></a>
        <a href="{{loop_path}}" download="{{loop_path}}"><button class="download-btn">download loop's data</button></a>

        <form method="POST" action="{% url 'task:custom_loop' task_id %}" id="loopForm" class="mt-2">
            {% csrf_token %}
            <br>
            <div class="d-flex name m-0">
                <label for="name" class="mt-2">Name:</label>
                <input type="text" id="name" name="name" class="form-control name" required>
            </div><br>

            <div class="d-flex m-0 id">
                <label for="id" class="id-label">ID:</label>
                <input type="text" id="id" name="id" class="form-control id" required>
            </div><br>
            <p>&emsp;&ensp;Generate a new loop by entering a new id.</p>
            <p>&emsp;&ensp;Edit a loop by entering that loop's id.</p>


            <div class="point mt-5 d-flex">
                <b>Point:</b><br>
                <div class="point-left mt-4">
                    <div class="d-flex mt-3 x1">
                        <label for="x1" class="m-2">x1:</label>
                        <input type="number" id="x1" name="x1" class="form-control x1" required>
                    </div>

                    <div class="d-flex mt-3 x2">
                        <label for="x2" class="m-2">x2:</label>
                        <input type="number" id="x2" name="x2" class="form-control x2" required>
                    </div>

                    <div class="d-flex mt-3 x3">
                        <label for="x3" class="m-2">x3:</label>
                        <input type="number" id="x3" name="x3" class="form-control x3" required>
                    </div>

                    <div class="d-flex mt-3 x4">
                        <label for="x4" class="m-2">x4:</label>
                        <input type="number" id="x4" name="x4" class="form-control x4" required>
                    </div>
                </div>

                <div class="point-right mt-4">
                    <div class="d-flex mt-3 y1">
                        <label for="y1" class="m-2">y1:</label>
                        <input type="number" id="y1" name="y1" class="form-control y1" required>
                    </div>

                    <div class="d-flex mt-3 y2">
                        <label for="y2" class="m-2">y2:</label>
                        <input type="number" id="y2" name="y2" class="form-control y2" required>
                    </div>

                    <div class="d-flex mt-3 y3">
                        <label for="y3" class="m-2">y3:</label>
                        <input type="number" id="y3" name="y3" class="form-control y3" required>
                    </div>

                    <div class="d-flex mt-3 y4">
                        <label for="y4" class="m-2">y4:</label>
                        <input type="number" id="y4" name="y4" class="form-control y4" required>
                    </div>
                </div>
            </div>

            <div class="plot-direction mt-4">
                <p class="mb-2">direction of plotting</p>
                <label>
                    <input type="radio" name="clock-choice" value="counterclockwise" checked> counterclockwise
                </label>
                <br>
                <label>
                    <input type="radio" name="clock-choice" value="clockwise"> clockwise
                </label>
            </div>

            <button type="submit" class="custom-loop submit-btn">Add loop's data</button>
        </form>
    </div>

    <div class="d-flex loop-custom-options">
        <a href="{% url 'task:schedule' task_id %}"><button class="all-done-btn m-4">Confirm Creation</button></a>
    </div>

    {% endif %}
</div>

{% endblock %}

SmartTrafficMonitoring/task/templates/task/index.html
{% extends 'task/layout.html' %} 
{% load static %} 
{% block body %}

    <!-- ============ task ============ -->
    <div class="task-area">
        <div class="d-flex task-menu">
            <div class="recent-task">RECENT TASK</div>
            <form class="d-flex search-task" action="{% url 'task:search_task' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
            <a class="create-task" href="{% url 'task:create_task' %}">CREATE TASK</a>
        </div>
    </div>
    <!-- ============= table ============= -->
    {% if tasks %}
    <div class="report-table">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">DATE</th>
                    <th scope="col">NAME</th>
                    <th scope="col">LOCATION</th>
                    <th scope="col">STATUS</th>
                    <th scope="col">DATE MODIFY</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                <tr>
                  <td>{{ task.created_at }}</td>
                  <td>{{ task.name }}</td>
                  <td>{{ task.location }}</td>
                  <td>{{ task.status_id }}</td>
                  <td>{{ task.updated_at }}</td>
                  <td class="actions-btn">
                    <a class="view-task-btn m-1" href="{% url 'task:view_task' task.id %}">VIEW</a>
                    {% if task.created_by == user %}
                    <a class="update-task-btn m-1" href="{% url 'task:update_task' task.id %}">UPDATE</a>
                    <!-- DELETE TASK -->
                    <button type="button" class="btn btn-danger delete-btn m-1" data-toggle="modal" data-target="#exampleModalCenter">
                      DELETE
                    </button>
                    <!-- DELETE TASK MODAL -->
                    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title text-danger" id="exampleModalLongTitle">Delete Task</h5>
                          </div>
                          <div class="modal-body">
                            <h5 class="text-muted">Do you want to delete this task?</h5>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <form action="{% url 'task:delete_task' task.id %}">
                                <input type="submit" class="btn btn-danger" value="Delete" />
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="report-table alert alert-danger">
        <strong>Info!</strong> {{ message }}
    </div>
    {% endif %}
{% endblock %}

SmartTrafficMonitoring/task/templates/task/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <!-- main css -->
    {% block style %}
    <link rel="stylesheet" type="text/css" href="../static/task/css/style.css">
    {% endblock %}
    <title>SMTM</title>
</head>
<!-- "{% static 'task/css/style.css' %}" -->
<body>
    <!-- ============ navbar ============ -->
    <div class="d-flex align-items-center fixed-top shadow nav" style="min-height: 56px; z-index: 5;">
        <div class="container-fluid">
            <div class="row align-items-center">
                <!-- search -->
                <div class="col d-flex align-items-center">
                    <!-- logo -->
                    <a href="{% url 'task:index' %}" class="navbar-brand"
                        style="color: #ffffff; font-size:25px; font-weight: 500">
                        Smart Traffic Monitoring
                    </a>
                </div>
                <!-- menus -->
                <div class="col d-flex align-items-center justify-content-end" style="color: #3F4682;">
                    <!-- notifications menu -->
                    <a href="{% url 'task:view_notification' %}" class="notification-dropdown">
                        <i class="fa-solid fa-bell"></i>
                    </a>
                    <!-- hamburger menu-->
                    <div class="d-flex align-items-center justify-content-center p-1 mx-2"
                        style="width: 38px; height: 38px; object-fit: cover" id="hamburger-menu"
                        data-bs-toggle="dropdown" aria-expanded="false" type="button" data-bs-auto-close="outside">
                        <i class="fa-solid fa-bars"></i>
                    </div>
                    <!-- hamburger dropdown -->
                    <ul class="dropdown-menu shadow p-3 m-1" aria-labelledby="hamburger-menu">
                        <div class="hamburger-dropdown">
                            <div>
                                <a href="{% url 'user:profile' %}" class="d-flex text-decoration-none p-1">
                                    <i class="fa-solid fa-user m-1"></i>
                                    <p class="m-0">View Profile</p>
                                </a>
                            </div>
                            <div>
                                <a href="{% url 'homepage:index' %}" class="d-flex text-decoration-none p-1">
                                    <i class="fa-solid fa-address-card m-1"></i>
                                    <p class="m-0">About Us</p>
                                </a>
                            </div>
                            <div>
                                <a href="{% url 'user:change_pw' %}" class="d-flex text-decoration-none p-1">
                                    <i class="fa-solid fa-lock m-1"></i>
                                    <p class="m-0">Change Password</p>
                                </a>
                            </div>
                            <div>
                                <a href="{% url 'user:logout' %}" class="d-flex text-decoration-none p-1">
                                    <i class="fa-solid fa-right-from-bracket m-1"></i>
                                    <p class="m-0">Logout</p>
                                </a>
                            </div>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>

{% block body %}
{% endblock %}

</html>

SmartTrafficMonitoring/task/templates/task/update_task.html
{% extends 'task/layout.html' %}
{% load static %}
{% block body %}

<div class="container m-7">
    <h1>Update Task</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'task:update_task' task.id %}">
        {% csrf_token %}

        <div class="d-flex name">
            <div class="d-flex name-box">
                <label for="name" class="form-label">Name:</label>
                <input class="form-control name-box" type="text" id="name" name="name" value="{{ task.name }}">
            </div>
        </div>

        <div class="d-flex location">
            <label for="location">Location</label>
            <input class="form-control name-box" type="text" id="location" name="location" value="{{ task.location }}">
        </div>
        <div class="d-flex location">
            <label for="latitude">Latitude</label>
            <input type="number" min="-90.00" max="90.00" class="form-control latitude" id="latitude" name="latitude" value="{{ task.latitude }}">
        </div>
        <div class="d-flex location">
            <label for="longitude">Longitude</label>
            <input type="number" min="-180.00" max="180.00" class="form-control longitude" id="longitude" name="longitude" value="{{ task.longitude }}">
        </div>
        <div class="d-flex description mt-5">
            <label for="note" class="form-label">Note</label><br>
            <textarea  class="form-control description-box" id="note" name="note" value="{{ task.note }}"></textarea>
        </div>  

        <div class="d-flex submit-area">
            <button type="submit" class="submit-btn">Update</button>
            <button type="button" class="cancel-btn"><a href="{% url 'task:view_task' task.id %}" class="cancel-btn">Cancel</a></button>
        </div>
    </form>
</div>

{% endblock %}