SmartTrafficMonitoring/SmartTrafficMonitoring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('homepage.urls', namespace='homepage')),
    path("", include('task.urls', namespace='task')),
    path("user/", include('user.urls', namespace='user')),
    path("accounts/", include("allauth.urls")),
]

SmartTrafficMonitoring/homepage/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='index')

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SmartTrafficMonitoring/task/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'task'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create-task/', views.create_task, name='create_task'),
    path('view-task/<int:task_id>', views.view_task, name='view_task'),
    path('update-task/<int:task_id>', views.update_task, name='update_task'),
    path('delete-task/<int:task_id>', views.delete_task, name='delete_task'),
    path('search-task', views.search_task, name='search_task'),
    path('custom-loop/<int:task_id>', views.custom_loop, name='custom_loop'),
    path('clear-loop/<int:task_id>', views.clear_loop, name='clear_loop'),
    path('delete-loop/<int:task_id>/<int:loop_id>', views.delete_loop, name='delete_loop'),
    path('schedule/<int:task_id>', views.schedule, name='schedule'),
    path('notification/', views.view_notification, name='view_notification'),
    path('map/', views.map, name='map'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SmartTrafficMonitoring/user/urls.py
from django.urls import path
from user.views import ChangePasswordView


from . import views
app_name = 'user'

urlpatterns = [
    #path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('profile', views.profile, name='profile'),
    path('change_pw', ChangePasswordView.as_view(), name='change_pw'),
    path('create_user', views.create_user, name='create_user'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
]

SmartTrafficMonitoring/homepage/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
from django.utils import dateformat
from django.db.models import Q

#import sys
#sys.path.append("../user")

#from user.models import UserInfo

#@login_required(login_url='/user/login')
def index(request):
    return render(request, 'homepage/homepage.html')

SmartTrafficMonitoring/homepage/templates/homepage/homepage.html
{% extends 'homepage/layout.html' %}
{% load static %}
{% block body %}

<body>

    <div id="hero" class="hero overlay">
        <div class="hero-content">
            <div class="hero-text">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-md-7">
                            <div class="hero-text-content">
                                <h1>Get Information</h1>
                                <p>Use drones to detect your area of interest!</p>
                                <p>Create Task, Create Loop</p>
                                <p>Wait for Result!</p>
                                <div class="d-flex submit-area">
                                    <!-- Uncomment and use these buttons if needed -->
                                    <!--
                                    <button type="submit" class="submit-btn"><a href="{% url 'task:index' %}" class="submit-btn">Report</a></button>
                                    <button type="submit" class="submit-btn"><a href="{% url 'task:create_task' %}" class="submit-btn">Create task</a></button>
                                    -->
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5 text-center">
                            <img src="{% static 'img/drones2.png' %}" alt="drones" class="img-fluid" style="padding: 10px; transform: scale(1.5);">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="decorative-hr">
        <hr>
    </div>

    <main id="main" class="site-main">
        <section class="site-section subpage-site-section section-contact-us">
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <div id="member" class="team-members">
                            <h2>Team Members</h2>
                            <ul>
                                <li>6410615048 - ณัฐชนน จันทร์รุ่งโรจน์</li>
                                <li>6410615063 - ธนากร ทองย้อย</li>
                                <li>6410685082 - กิตติศักดิ์ สุดแดน</li>
                                <li>6410685124 - ธนกฤต อิ้ววังโส</li>
                                <li>6410685199 - ปริญญ์ ยิ้มรุ่งเรือง</li>
                                <li>6410685207 - ปริวรรต สวัสดิ์ชาติ</li>
                            </ul>
                            <br>
                            <h3>Link</h3>
                            <p>If you want to learn more about our project, visit our <a href="https://github.com/6410685082/CN332_AAA.git" target="_blank">Github repository</a>.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <style>
        .decorative-hr {
            text-align: center;
            margin: 1rem 0;
        }
        .decorative-hr hr {
            border: 0;
            height: 2px;
            background-image: linear-gradient(to right, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0));
            margin: 0 auto;
            width: 90%;
        }
    </style>
</body>
{% endblock %}

SmartTrafficMonitoring/homepage/templates/homepage/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <!-- main css -->
    <link rel="stylesheet" type="text/css" href="../static/style.css">
    <!-- {% static 'style.css' %} -->
    <title>SMTM</title>
</head>

<body>

    <!-- ============ navbar ============ -->
    <div class="d-flex align-items-center fixed-top shadow nav" style="min-height: 56px; z-index: 5;">
        <div class="container-fluid">
            <div class="row align-items-center">
                <!-- search -->
                <div class="col d-flex align-items-center">
                    <!-- logo -->
                    <a href="{% url 'task:index' %}" class="navbar-brand"
                        style="color: #ffffff; font-size:25px; font-weight: 500">
                        Smart Traffic Monitoring
                    </a>
                </div>
                <!-- menus -->
                <div class="col d-flex align-items-center justify-content-end" style="color: #3F4682;">
                    <!-- Check if the user is logged in -->
                    {% if user.is_authenticated %}
                        <!-- notifications menu -->
                        <a href="{% url 'task:view_notification' %}" class="notification-dropdown">
                            <i class="fa-solid fa-bell"></i>
                        </a>
                        <!-- hamburger menu-->
                        <div class="d-flex align-items-center justify-content-center p-1 mx-2"
                            style="width: 38px; height: 38px; object-fit: cover" id="hamburger-menu"
                            data-bs-toggle="dropdown" aria-expanded="false" type="button" data-bs-auto-close="outside">
                            <i class="fa-solid fa-bars"></i>
                        </div>
                        <!-- hamburger dropdown -->
                        <ul class="dropdown-menu shadow p-3 m-1" aria-labelledby="hamburger-menu">
                            <div class="hamburger-dropdown">
                                <div>
                                    <a href="{% url 'user:profile' %}" class="d-flex text-decoration-none p-1">
                                        <i class="fa-solid fa-user m-1"></i>
                                        <p class="m-0">View Profile</p>
                                    </a>
                                </div>
                                <div>
                                    <a href="{% url 'homepage:index' %}" class="d-flex text-decoration-none p-1">
                                        <i class="fa-solid fa-address-card m-1"></i>
                                        <p class="m-0">About Us</p>
                                    </a>
                                </div>
                                <div>
                                    <a href="{% url 'user:change_pw' %}" class="d-flex text-decoration-none p-1">
                                        <i class="fa-solid fa-lock m-1"></i>
                                        <p class="m-0">Change Password</p>
                                    </a>
                                </div>
                                <div>
                                    <a href="{% url 'user:logout' %}" class="d-flex text-decoration-none p-1">
                                        <i class="fa-solid fa-right-from-bracket m-1"></i>
                                        <p class="m-0">Logout</p>
                                    </a>
                                </div>
                            </div>
                        </ul>
                    {% else %}
                        <!-- Show login and sign up options -->
                        <div class="d-flex align-items-center justify-content-center p-1 mx-2">
                            <a href="{% url 'user:login' %}" class="d-flex text-decoration-none p-1">
                                <i class='fas fa-sign-in-alt m-1'></i>
                                <p class="m-0">Sign in</p>
                            </a>
                        </div>
                        <div class="d-flex align-items-center justify-content-center p-1 mx-2">
                            <a href="{% url 'user:create_user' %}" class="d-flex text-decoration-none p-1">
                                <i class='fas fa-sign-in-alt m-1'></i>
                                <p class="m-0">Sign up</p>
                            </a>
                        </div>
                    {% endif%}
                </div>
            </div>
        </div>
    </div>
</body>

{% block body %}
{% endblock %}

<body>
    <!-- Favicon
    ================================================== -->
    <link rel="icon"  type="image/x-icon" sizes="180x180" href="../../static/img/drone-icon.png">
    <link rel="drone-icon" type="image/png" sizes="1080x1080" href="../../static/img/drones.png">
    


    <footer style="float: right; margin-right: 8rem;">
        <div>
            <div class="container">
                <div class="row">
                    <div class="col-xs-4">
                        <div class="copy-right">
                            <p>&copy; SmartTrafficMonitoring</p>
                            <p>All Rights Reserved</p>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.copyright -->
    </footer><!-- /#footer -->
</body>
</html>